In [1]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark.sql import functions as F
from pyspark.sql.types import *

sc = SparkContext.getOrCreate()
spark = SparkSession.builder.getOrCreate()
sqlContext = SQLContext(sc)

# Layer1 : Datalake

In [4]:
layer = 1
table = "tweets"
path = f"../layer{layer}/{table}/"
tweets = spark.read.parquet(path)
tweets.toPandas()

,tweet_id,created_at,text,hashtags,retweet_count,possibly_sensitive,lang,user_id,user_name,user_description,user_verification,user_followers_count,user_friends_count,user_created_at,user_location,etl_load,etl_load_partition_year,etl_load_partition_month,etl_load_partition_day,etl_load_partition_hour
0,1359253319861026818,Tue Feb 09 21:30:19 +0000 2021,RT @TNTSportsBR: DESFALQUES! Dois jogadores do...,,0,None,pt,1198710796286676993,Corinthians Tim√£o,S . C . Corinthians . P - VAI CORINTHIANS ! ‚ö™‚ö´...,False,422,1063,Sun Nov 24 21:12:13 +0000 2019,None,2021-02-09 18:30:35.713,2021,2,9,18
1,1359253318258819072,Tue Feb 09 21:30:19 +0000 2021,RT @GFiuza_Oficial: Onde est√£o os democratas p...,,0,None,pt,1266403333415239680,Conde von Roscoff,"Penso, logo existo, ou algo bem parecido.",False,79,610,Fri May 29 16:17:57 +0000 2020,None,2021-02-09 18:30:35.713,2021,2,9,18
2,1359253330556575744,Tue Feb 09 21:30:22 +0000 2021,RT @CNNBrasil: Amazonas recebe mais de 62 mil ...,,0,False,pt,122272543,Japax√© Brazueiros e Brazueiras,Brazueiros e Brazueiras\n\nJapon√™s Baiano n√£o ...,False,1670,4993,Fri Mar 12 04:53:50 +0000 2010,Japones Baiano,2021-02-09 18:30:35.713,2021,2,9,18
3,1359253330665627665,Tue Feb 09 21:30:22 +0000 2021,@flavioclaudir Confira! üòéüòéV√çDEO NOVO no Canal....,"consci√™ncia, empatia, covid, quarentena, pande...",0,False,pt,215139198,K√°ssia Rocha,"Tenho 36 anos. YouTuber, Escritora, Professora...",False,1254,133,Sat Nov 13 02:54:30 +0000 2010,Brasil,2021-02-09 18:30:35.713,2021,2,9,18
4,1359253331823239181,Tue Feb 09 21:30:22 +0000 2021,RT @noticiaaominuto: Covid-19. Madeira com mai...,"paisaominuto,",0,False,pt,102647685,Micaela Campan√°rio,None,False,88,798,Thu Jan 07 11:13:19 +0000 2010,Funchal,2021-02-09 18:30:35.713,2021,2,9,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,1359252876669943817,Tue Feb 09 21:28:34 +0000 2021,RT @aramalhocorreia: N√£o h√° um jornalista q te...,,0,None,pt,14582157,Mac Free,O tempo em directo..... em Le√ßa da Palmeira\nW...,False,34,118,Tue Apr 29 08:13:53 +0000 2008,"Le√ßa da Palmeira, Portugal",2021-02-09 18:29:28.339,2021,2,9,18
171,1359252877643034630,Tue Feb 09 21:28:34 +0000 2021,Fica bem,,0,None,pt,1246890076019326978,@mery2013silva,None,False,408,1003,Sun Apr 05 19:59:15 +0000 2020,None,2021-02-09 18:29:28.339,2021,2,9,18
172,1359252885423464450,Tue Feb 09 21:28:36 +0000 2021,RT @fabioirodrigues: Sabemos que a Covid-19 n√£...,,0,None,pt,926801470158180352,luanalua,None,False,144,353,Sat Nov 04 13:21:04 +0000 2017,None,2021-02-09 18:29:28.339,2021,2,9,18
173,1359252885645758465,Tue Feb 09 21:28:36 +0000 2021,‚ö°Ô∏è ‚ÄúSenador Jos√© Maranh√£o morre de covid-19‚Äù d...,,0,False,pt,72694672,Ricardo üáßüá∑,üáßüá∑ Crist√£o üáßüá∑ Conservador üáßüá∑\n\nPARLER @Ricardo2,False,51621,51660,Tue Sep 08 22:56:17 +0000 2009,Brasil,2021-02-09 18:29:28.339,2021,2,9,18
174,1359252891719106560,Tue Feb 09 21:28:37 +0000 2021,Vamo pro bar comemorar @jdoriajr,,0,None,pt,219621165,Pedro ‚Ñ¢ ‚ùÅ,Have you met Ted? Nothing good happens after 2...,False,1963,416,Thu Nov 25 11:25:12 +0000 2010,"S√£o Paulo, Brasil",2021-02-09 18:29:28.339,2021,2,9,18

# Layer2

## Fact_tweet

In [5]:
layer = 2
table = "fact_tweet"
path = f"../layer{layer}/{table}/"
fact_tweet = spark.read.parquet(path)
fact_tweet.toPandas()

,tweet_id,created_at,text,hashtags,retweet_count,possibly_sensitive,lang,user_id,created_at_partition_year,created_at_partition_month,created_at_partition_day,created_at_partition_hour
0,1359253267029446656,2021-02-09 18:30:07,RT @elikatakimoto: Fui ali na padaria e estava...,None,0,None,pt,1104490014623318016,2021,2,9,18
1,1359253271022559242,2021-02-09 18:30:08,RT @danielPMERJ: Foi por conta dessas abomina√ß...,None,0,None,pt,43881647,2021,2,9,18
2,1359253272763195397,2021-02-09 18:30:08,A pessoa mais velha da Europa sobrevive a Covi...,None,0,None,pt,1123258543505850368,2021,2,9,18
3,1359253274508066819,2021-02-09 18:30:09,@wallaceprecioso Confira! üòéüòéV√çDEO NOVO no Cana...,"consci√™ncia, empatia, covid, quarentena, pandemia",0,False,pt,215139198,2021,2,9,18
4,1359253276299059204,2021-02-09 18:30:09,RT @freibetto: A pandemia √© o segundo aconteci...,None,0,None,pt,291292275,2021,2,9,18
...,...,...,...,...,...,...,...,...,...,...,...,...
2795,1359252876669943817,2021-02-09 18:28:34,RT @aramalhocorreia: N√£o h√° um jornalista q te...,None,0,None,pt,14582157,2021,2,9,18
2796,1359252877643034630,2021-02-09 18:28:34,Fica bem,None,0,None,pt,1246890076019326978,2021,2,9,18
2797,1359252885423464450,2021-02-09 18:28:36,RT @fabioirodrigues: Sabemos que a Covid-19 n√£...,None,0,None,pt,926801470158180352,2021,2,9,18
2798,1359252885645758465,2021-02-09 18:28:36,‚ö°Ô∏è ‚ÄúSenador Jos√© Maranh√£o morre de covid-19‚Äù d...,None,0,False,pt,72694672,2021,2,9,18
2799,1359252891719106560,2021-02-09 18:28:37,Vamo pro bar comemorar @jdoriajr,None,0,None,pt,219621165,2021,2,9,18

## Dim_user

In [6]:
layer = 2
table = "dim_user"
path = f"../layer{layer}/{table}/"
dim_user = spark.read.parquet(path)
dim_user.toPandas()

,user_id,user_name,user_description,user_verification,user_followers_count,user_friends_count,user_created_at,user_location
0,1198710796286676993,Corinthians Tim√£o,S . C . Corinthians . P - VAI CORINTHIANS ! ‚ö™‚ö´...,False,422,1063,2019-11-24 18:12:13,None
1,1266403333415239680,Conde von Roscoff,"Penso, logo existo, ou algo bem parecido.",False,79,610,2020-05-29 13:17:57,None
2,122272543,Japax√© Brazueiros e Brazueiras,Brazueiros e Brazueiras\n\nJapon√™s Baiano n√£o ...,False,1670,4993,2010-03-12 01:53:50,Japones Baiano
3,215139198,K√°ssia Rocha,"Tenho 36 anos. YouTuber, Escritora, Professora...",False,1254,133,2010-11-12 23:54:30,Brasil
4,102647685,Micaela Campan√°rio,None,False,88,798,2010-01-07 08:13:19,Funchal
...,...,...,...,...,...,...,...,...
2620,14582157,Mac Free,O tempo em directo..... em Le√ßa da Palmeira\nW...,False,34,118,2008-04-29 05:13:53,"Le√ßa da Palmeira, Portugal"
2621,1246890076019326978,@mery2013silva,None,False,408,1003,2020-04-05 16:59:15,None
2622,926801470158180352,luanalua,None,False,144,353,2017-11-04 10:21:04,None
2623,72694672,Ricardo üáßüá∑,üáßüá∑ Crist√£o üáßüá∑ Conservador üáßüá∑\n\nPARLER @Ricardo2,False,51621,51660,2009-09-08 19:56:17,Brasil
2624,219621165,Pedro ‚Ñ¢ ‚ùÅ,Have you met Ted? Nothing good happens after 2...,False,1963,416,2010-11-25 08:25:12,"S√£o Paulo, Brasil"